sudo: required

services:
    - docker

before_install:
    - docker pull eboraas/debian:stable

script:
    - docker run --rm=true -v `pwd`:/debian-bootstrap:rw eboraas/debian:stable /bin/bash -c "/debian-bootstrap/run.sh"

notifications:
  email: false
