sudo: required

script:
    - sudo bash run.sh

services:
    - docker

before_install:
    - docker pull debian

script:
    - docker run --rm=true -v `pwd`:/debian-bootstrap:rw debian /bin/bash -c "/debian-bootstrap/run.sh"

notifications:
  email: false
