sudo: required

script:
    - sudo bash run.sh

services:
      - docker

before_install:
    - docker pull debian
    - docker run debian /bin/sh -c "wget -O - -o /dev/null  https://raw.githubusercontent.com/jyvet/debian-bootstrap/master/run.sh | bash"

script:
    - wget -O - -o /dev/null  https://raw.githubusercontent.com/jyvet/debian-bootstrap/master/run.sh | bash
